// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mysql "github.com/nikita5637/quiz-fetcher/internal/pkg/storage/mysql"
	mock "github.com/stretchr/testify/mock"
)

// SyncLogStorage is an autogenerated mock type for the SyncLogStorage type
type SyncLogStorage struct {
	mock.Mock
}

type SyncLogStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *SyncLogStorage) EXPECT() *SyncLogStorage_Expecter {
	return &SyncLogStorage_Expecter{mock: &_m.Mock}
}

// CreateSyncLog provides a mock function with given fields: ctx, sync
func (_m *SyncLogStorage) CreateSyncLog(ctx context.Context, sync mysql.SyncLog) (int, error) {
	ret := _m.Called(ctx, sync)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mysql.SyncLog) (int, error)); ok {
		return rf(ctx, sync)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mysql.SyncLog) int); ok {
		r0 = rf(ctx, sync)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, mysql.SyncLog) error); ok {
		r1 = rf(ctx, sync)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncLogStorage_CreateSyncLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSyncLog'
type SyncLogStorage_CreateSyncLog_Call struct {
	*mock.Call
}

// CreateSyncLog is a helper method to define mock.On call
//   - ctx context.Context
//   - sync mysql.SyncLog
func (_e *SyncLogStorage_Expecter) CreateSyncLog(ctx interface{}, sync interface{}) *SyncLogStorage_CreateSyncLog_Call {
	return &SyncLogStorage_CreateSyncLog_Call{Call: _e.mock.On("CreateSyncLog", ctx, sync)}
}

func (_c *SyncLogStorage_CreateSyncLog_Call) Run(run func(ctx context.Context, sync mysql.SyncLog)) *SyncLogStorage_CreateSyncLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mysql.SyncLog))
	})
	return _c
}

func (_c *SyncLogStorage_CreateSyncLog_Call) Return(_a0 int, _a1 error) *SyncLogStorage_CreateSyncLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SyncLogStorage_CreateSyncLog_Call) RunAndReturn(run func(context.Context, mysql.SyncLog) (int, error)) *SyncLogStorage_CreateSyncLog_Call {
	_c.Call.Return(run)
	return _c
}

// FindLastSync provides a mock function with given fields: ctx, name
func (_m *SyncLogStorage) FindLastSync(ctx context.Context, name string) ([]mysql.SyncLog, error) {
	ret := _m.Called(ctx, name)

	var r0 []mysql.SyncLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]mysql.SyncLog, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []mysql.SyncLog); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mysql.SyncLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncLogStorage_FindLastSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastSync'
type SyncLogStorage_FindLastSync_Call struct {
	*mock.Call
}

// FindLastSync is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *SyncLogStorage_Expecter) FindLastSync(ctx interface{}, name interface{}) *SyncLogStorage_FindLastSync_Call {
	return &SyncLogStorage_FindLastSync_Call{Call: _e.mock.On("FindLastSync", ctx, name)}
}

func (_c *SyncLogStorage_FindLastSync_Call) Run(run func(ctx context.Context, name string)) *SyncLogStorage_FindLastSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SyncLogStorage_FindLastSync_Call) Return(_a0 []mysql.SyncLog, _a1 error) *SyncLogStorage_FindLastSync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SyncLogStorage_FindLastSync_Call) RunAndReturn(run func(context.Context, string) ([]mysql.SyncLog, error)) *SyncLogStorage_FindLastSync_Call {
	_c.Call.Return(run)
	return _c
}

// PatchSyncLog provides a mock function with given fields: ctx, sync
func (_m *SyncLogStorage) PatchSyncLog(ctx context.Context, sync mysql.SyncLog) error {
	ret := _m.Called(ctx, sync)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mysql.SyncLog) error); ok {
		r0 = rf(ctx, sync)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncLogStorage_PatchSyncLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchSyncLog'
type SyncLogStorage_PatchSyncLog_Call struct {
	*mock.Call
}

// PatchSyncLog is a helper method to define mock.On call
//   - ctx context.Context
//   - sync mysql.SyncLog
func (_e *SyncLogStorage_Expecter) PatchSyncLog(ctx interface{}, sync interface{}) *SyncLogStorage_PatchSyncLog_Call {
	return &SyncLogStorage_PatchSyncLog_Call{Call: _e.mock.On("PatchSyncLog", ctx, sync)}
}

func (_c *SyncLogStorage_PatchSyncLog_Call) Run(run func(ctx context.Context, sync mysql.SyncLog)) *SyncLogStorage_PatchSyncLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mysql.SyncLog))
	})
	return _c
}

func (_c *SyncLogStorage_PatchSyncLog_Call) Return(_a0 error) *SyncLogStorage_PatchSyncLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SyncLogStorage_PatchSyncLog_Call) RunAndReturn(run func(context.Context, mysql.SyncLog) error) *SyncLogStorage_PatchSyncLog_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewSyncLogStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewSyncLogStorage creates a new instance of SyncLogStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSyncLogStorage(t mockConstructorTestingTNewSyncLogStorage) *SyncLogStorage {
	mock := &SyncLogStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
