// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nikita5637/quiz-fetcher/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// SyncLogsFacade is an autogenerated mock type for the SyncLogsFacade type
type SyncLogsFacade struct {
	mock.Mock
}

type SyncLogsFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *SyncLogsFacade) EXPECT() *SyncLogsFacade_Expecter {
	return &SyncLogsFacade_Expecter{mock: &_m.Mock}
}

// CreateSyncLog provides a mock function with given fields: ctx, syncLog
func (_m *SyncLogsFacade) CreateSyncLog(ctx context.Context, syncLog model.SyncLog) (model.SyncLog, error) {
	ret := _m.Called(ctx, syncLog)

	var r0 model.SyncLog
	if rf, ok := ret.Get(0).(func(context.Context, model.SyncLog) model.SyncLog); ok {
		r0 = rf(ctx, syncLog)
	} else {
		r0 = ret.Get(0).(model.SyncLog)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.SyncLog) error); ok {
		r1 = rf(ctx, syncLog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncLogsFacade_CreateSyncLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSyncLog'
type SyncLogsFacade_CreateSyncLog_Call struct {
	*mock.Call
}

// CreateSyncLog is a helper method to define mock.On call
//  - ctx context.Context
//  - syncLog model.SyncLog
func (_e *SyncLogsFacade_Expecter) CreateSyncLog(ctx interface{}, syncLog interface{}) *SyncLogsFacade_CreateSyncLog_Call {
	return &SyncLogsFacade_CreateSyncLog_Call{Call: _e.mock.On("CreateSyncLog", ctx, syncLog)}
}

func (_c *SyncLogsFacade_CreateSyncLog_Call) Run(run func(ctx context.Context, syncLog model.SyncLog)) *SyncLogsFacade_CreateSyncLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SyncLog))
	})
	return _c
}

func (_c *SyncLogsFacade_CreateSyncLog_Call) Return(_a0 model.SyncLog, _a1 error) *SyncLogsFacade_CreateSyncLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetLastSync provides a mock function with given fields: ctx, name
func (_m *SyncLogsFacade) GetLastSync(ctx context.Context, name string) (model.SyncLog, error) {
	ret := _m.Called(ctx, name)

	var r0 model.SyncLog
	if rf, ok := ret.Get(0).(func(context.Context, string) model.SyncLog); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.SyncLog)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncLogsFacade_GetLastSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSync'
type SyncLogsFacade_GetLastSync_Call struct {
	*mock.Call
}

// GetLastSync is a helper method to define mock.On call
//  - ctx context.Context
//  - name string
func (_e *SyncLogsFacade_Expecter) GetLastSync(ctx interface{}, name interface{}) *SyncLogsFacade_GetLastSync_Call {
	return &SyncLogsFacade_GetLastSync_Call{Call: _e.mock.On("GetLastSync", ctx, name)}
}

func (_c *SyncLogsFacade_GetLastSync_Call) Run(run func(ctx context.Context, name string)) *SyncLogsFacade_GetLastSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SyncLogsFacade_GetLastSync_Call) Return(_a0 model.SyncLog, _a1 error) *SyncLogsFacade_GetLastSync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// PatchSyncLog provides a mock function with given fields: ctx, syncLog
func (_m *SyncLogsFacade) PatchSyncLog(ctx context.Context, syncLog model.SyncLog) (model.SyncLog, error) {
	ret := _m.Called(ctx, syncLog)

	var r0 model.SyncLog
	if rf, ok := ret.Get(0).(func(context.Context, model.SyncLog) model.SyncLog); ok {
		r0 = rf(ctx, syncLog)
	} else {
		r0 = ret.Get(0).(model.SyncLog)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.SyncLog) error); ok {
		r1 = rf(ctx, syncLog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SyncLogsFacade_PatchSyncLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchSyncLog'
type SyncLogsFacade_PatchSyncLog_Call struct {
	*mock.Call
}

// PatchSyncLog is a helper method to define mock.On call
//  - ctx context.Context
//  - syncLog model.SyncLog
func (_e *SyncLogsFacade_Expecter) PatchSyncLog(ctx interface{}, syncLog interface{}) *SyncLogsFacade_PatchSyncLog_Call {
	return &SyncLogsFacade_PatchSyncLog_Call{Call: _e.mock.On("PatchSyncLog", ctx, syncLog)}
}

func (_c *SyncLogsFacade_PatchSyncLog_Call) Run(run func(ctx context.Context, syncLog model.SyncLog)) *SyncLogsFacade_PatchSyncLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SyncLog))
	})
	return _c
}

func (_c *SyncLogsFacade_PatchSyncLog_Call) Return(_a0 model.SyncLog, _a1 error) *SyncLogsFacade_PatchSyncLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewSyncLogsFacade interface {
	mock.TestingT
	Cleanup(func())
}

// NewSyncLogsFacade creates a new instance of SyncLogsFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSyncLogsFacade(t mockConstructorTestingTNewSyncLogsFacade) *SyncLogsFacade {
	mock := &SyncLogsFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
