[database]
address = "database"
dbname = "fetcher"
driver = "mysql"
port = 3306
	[database.credentials]
	username = "quiz_regbot"
	password = "TOPSECRET"

[fetcher]
	[fetcher.games]
	disabled_leagues = []
	enabled = true
	period = 3600
	[fetcher.registrator_api]
	address = "registrator-api"
	port = 8080

[log]
level = "info"
module_name = "fetcher"
	[log.elastic]
	address = "elasticsearch"
	enabled = true
	index = "quiz_regbot"
	port = 9200