database:
  address: "database"
  dbname: "fetcher"
  driver: "mysql"
  port: 3306
  credentials:
    username: "quiz_regbot"
    password: "TOPSECRET"

fetcher:
  registrator_api:
    address: "registrator-api"
    port: 8080

log:
  level: "info"
  elastic:
    address: "elasticsearch"
    enabled: true
    index: "quiz_regbot"
    port: 9200
  module_name: "fetcher"

synchronizer:
  sync:
    timeout: 600
  syncer:
    games:
      disabled_leagues: []
      enabled: true
      name: "games"
      period: 3600
    results:
      disabled_leagues: []
      enabled: true
      name: "results"
      period: 3600
      team: "SUPERTEAM"