#Log level
log_level = "info"
elastic_address = "elasticsearch"
elastic_port = 9200
elastic_index = "quiz_regbot"
elastic_logs_enabled = true

#
# Syncer config
#
disabled_games_fetchers = []
games_syncer_enabled = true
games_syncer_period = 3600
registrator_api_address = "registrator-api"
registrator_api_port = 8080

#
# DB Settings
#
driver = "mysql"
database_address = "mysql"
database_name = "fetcher"
database_port = 3306
database_username = "quiz_regbot"
