version: "3.9"

services:
  fetcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PATH: https://github.com/nikita5637/quiz-fetcher.git
        BRANCH: v1.0
    command: "/bin/fetcher --config /etc/config.toml"
    container_name: fetcher
    environment:
      DATABASE_CREDENTIALS_PASSWORD: quiz_regbot
    networks:
      - network

networks:
  network:
    driver: bridge
