version: "3.9"

services:
  fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/bin/fetcher --config /etc/config.yaml"
    container_name: fetcher
    env_file:
      - path: .env
        required: true
    networks:
      - network

networks:
  network:
    driver: bridge
