// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nikita5637/quiz-fetcher/internal/pkg/model"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

type Fetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Fetcher) EXPECT() *Fetcher_Expecter {
	return &Fetcher_Expecter{mock: &_m.Mock}
}

// GetGamesList provides a mock function with given fields: ctx
func (_m *Fetcher) GetGamesList(ctx context.Context) ([]model.Game, error) {
	ret := _m.Called(ctx)

	var r0 []model.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Game, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Game); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fetcher_GetGamesList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGamesList'
type Fetcher_GetGamesList_Call struct {
	*mock.Call
}

// GetGamesList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Fetcher_Expecter) GetGamesList(ctx interface{}) *Fetcher_GetGamesList_Call {
	return &Fetcher_GetGamesList_Call{Call: _e.mock.On("GetGamesList", ctx)}
}

func (_c *Fetcher_GetGamesList_Call) Run(run func(ctx context.Context)) *Fetcher_GetGamesList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Fetcher_GetGamesList_Call) Return(_a0 []model.Game, _a1 error) *Fetcher_GetGamesList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Fetcher_GetGamesList_Call) RunAndReturn(run func(context.Context) ([]model.Game, error)) *Fetcher_GetGamesList_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeagueID provides a mock function with given fields:
func (_m *Fetcher) GetLeagueID() int32 {
	ret := _m.Called()

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// Fetcher_GetLeagueID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeagueID'
type Fetcher_GetLeagueID_Call struct {
	*mock.Call
}

// GetLeagueID is a helper method to define mock.On call
func (_e *Fetcher_Expecter) GetLeagueID() *Fetcher_GetLeagueID_Call {
	return &Fetcher_GetLeagueID_Call{Call: _e.mock.On("GetLeagueID")}
}

func (_c *Fetcher_GetLeagueID_Call) Run(run func()) *Fetcher_GetLeagueID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Fetcher_GetLeagueID_Call) Return(_a0 int32) *Fetcher_GetLeagueID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Fetcher_GetLeagueID_Call) RunAndReturn(run func() int32) *Fetcher_GetLeagueID_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with given fields:
func (_m *Fetcher) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Fetcher_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Fetcher_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Fetcher_Expecter) GetName() *Fetcher_GetName_Call {
	return &Fetcher_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Fetcher_GetName_Call) Run(run func()) *Fetcher_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Fetcher_GetName_Call) Return(_a0 string) *Fetcher_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Fetcher_GetName_Call) RunAndReturn(run func() string) *Fetcher_GetName_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFetcher interface {
	mock.TestingT
	Cleanup(func())
}

// NewFetcher creates a new instance of Fetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFetcher(t mockConstructorTestingTNewFetcher) *Fetcher {
	mock := &Fetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
